project:
  type: website
  output-dir: docs

website:
  title: "Steve B. Holt"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
    
    background: light

format:
  html:
    theme: cosmo
      light: flatly
      dark: darkly
    css: styles.css
    toc: true

editor: visual

