project:
  type: website
  output-dir: docs

website:
  title: "Steve B. Holt"
  navbar:
    background: light
    search: true
    left:
      - text: "About"
        file: index.qmd
      - text: "Research"
        file: research.qmd
      - text: "Teaching"
        file: teaching.qmd
      - text: "Curriculum Vitae"
        file: cv.qmd
      - text: "Resources"
        file: resources.qmd
    

  sidebar: 
    - title: "Research"
      style: "docked"
      search: true
      logo: profile.png
      contents:
        - research.qmd
        - waiting.qmd
        - grading.qmd
        - referrals.qmd
        - charter.qmd
        - mentalhealth.qmd
        - altruism.qmd
        - ocb.qmd
        - givetime.qmd
        - rookie.qmd
        - prisons.qmd
        - millennials.qmd
        - nursinghome.qmd
        - civics.qmd
        - absences.qmd
        - sector.qmd
        - expectations.qmd
        - homework.qmd
        
    - title: "Teaching"
      contents:
        - teaching.qmd
        
    - title: "CV"
      contents:
        - cv.qmd
        
    - title: "Resources"
      contents:
        - resources.qmd
        - mpa.qmd
        - data.qmd
      

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
    toc: true

editor: visual
