project:
  type: website
  output-dir: docs

website:
  title: "Steve B. Holt"
  navbar:
    left:
      - text: "About"
        file: index.qmd
      - text: "Research"
        file: research.qmd
      - text: "Teaching"
        file: teaching.qmd
      - text: "Curriculum Vitae"
        file: cv.qmd
      - text: "Resources"
        file: resources.qmd
    
    background: light

  sidebar: 
    - title: "About"
      style: "docked"
      search: true
      logo: profile.png
      contents:
        - href: index.qmd
        - href: research.qmd
        - href: teaching.qmd
        - href: cv.qmd
    
    - title: "Research"
      contents:
        - href: research.qmd
        - href: homework.qmd

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
    toc: true

editor: visual

