---
title: "Useful Data"
---

### Publicly Available Data

-   [NBER Public Use Data Archive](https://www.nber.org/research/data?page=1&perPage=50)
-   [IPUMS Data Center - Census Microdata](https://usa.ipums.org/usa/)
-   [Common Core of Data - NCES School Data](https://nces.ed.gov/ccd/)
-   [American Time Use Survey](https://www.bls.gov/tus/data.htm)
-   [ATUS - IPUMS Version](https://www.atusdata.org/atus/)
-   [Federal Employee Viewpoint Survey](https://www.opm.gov/fevs/)
-   [National Longitudinal Survey of Youth](https://www.nlsinfo.org/investigator/pages/login)
-   [ICPSR Replication Data Reesitory](https://www.icpsr.umich.edu/web/pages/)
-   [American Community Survey](https://www.census.gov/programs-surveys/acs/data/summary-file.html)
-   [CDC National Health Interview Survey](https://www.cdc.gov/nchs/surveys.htm)
-   [Economic Development Data](http://devecondata.blogspot.com/)
-   [Project STAR Data](https://dataverse.harvard.edu/dataset.xhtml?persistentId=hdl:1902.1/10766)
-   [IPEDS Data - Higher Education Data](https://nces.ed.gov/ipeds/use-the-data)
-   [Education Longitudinal Study of 2002](https://nces.ed.gov/surveys/els2002/avail_data.asp)
-   [ICMA Data on Local Government Managers](https://icma.org/survey-research-datasets)
-   [Census of Governments Data](https://www.census.gov/programs-surveys/cog/data.html)
-   [NY Federal Reserve Microdata](https://www.newyorkfed.org/microeconomics/databank.html)
-   [Bureau of Economic Analysis Data](https://www.bea.gov/data/by-place-states-territories)
-   [Urban Institute State and Local Finance Data](https://state-local-finance-data.taxpolicycenter.org/pages.cfm)
-   [Bureau of Labor Statistics Employment Data](https://www.bls.gov/ces/data/home.htm)
-   [NYC Open Data](https://opendata.cityofnewyork.us/data/)
-   [Juvenile Justice Data](https://www.ojjdp.gov/ojstatbb/compendium/asp/Compendium.asp?selData=4)
-   [NIBRS for Crime Data](https://www.icpsr.umich.edu/web/NACJD/series/128#)
-   [CDC Wonder Data for Death Certificates](https://wonder.cdc.gov/)
-   [Poverty Action Lab](https://www.povertyactionlab.org/catalog-administrative-data-sets)
