---
title: "On the Margin"
---

### On the Margin: Who Receives a Juvenile Referral in School and What Effect Does It Have?

#### Abstract

Involvement with the juvenile justice system carries immense personal costs to youth: 30% of detained youth drop out of school (relative to 5% nationally) and 55% are re-arrested within one year. These personal costs are compounded by societal costs – both directly in $214,000 of expenses per confined youth per year – and indirectly in lost social and economic productivity. While much of the extant research on the “school-to-prison pipeline” focuses on school disciplinary practices such as suspension, less attention has been given to understanding the impact of school referrals to the juvenile justice system on students’ relationship with school. Using novel administrative data from North Carolina, we link 3 years of individual educational and disciplinary infraction records to juvenile justice system records to identify the effect of juvenile justice referrals for school-based offenses on student academic and behavioral outcomes. We find that, even for the same offense type and circumstance, relative to students only punished for infractions internally in the school, students referred to juvenile justice experience lower academic achievement, increased absenteeism, and are more likely to be involved in future juvenile system contact. We show that these juvenile referrals are not inevitable and instead reflect a series of discretionary choices made by school administrators and law enforcement. Moreover, we examine demographic disparities in school-based referrals to juvenile justice and find that female students, Black students, and economically disadvantaged students are more likely to receive referrals even for the same offense type and circumstances. 

#### Citation

Sorensen, L. C., Headley, A., & Holt, S. B. (2024) On the Margin: Who Receives a Juvenile Referral in School and What Effect Does It Have?. *EdWorkingPaper: 24-907*.  Retrieved from Annenberg Institute at Brown University: https://doi.org/10.26300/k541-d383

[Full Text](https://edworkingpapers.com/sites/default/files/ai24-907.pdf)