---
title: "Giving Time"
---

### Giving Time: Examining Sector Differences in Volunteering Intensity

#### Abstract
Sector differences in prosocial motivations and behaviors among workers receives a great deal of attention in public administration scholarship. Extant literature consistently finds public sector workers are more likely to engage in prosocial behaviors, such as volunteering, than their peers in the private sector. Less attention has been paid to the sector gap in volunteerism along the intensive margin. Using time-diary data, which accounts for potential social desirability bias, from a nationally representative sample, this study investigates the gap between public sector workers and their private sector counterparts. The results suggest that public sector workers spend more time, on an average day, volunteering than observably similar private sector peers, and the difference cannot be explained by other observable differences between public and private sector workers. The gap in volunteer intensity is largest at the local level and among teachers. The implications of these results for research and practice are discussed.

#### Citation
Holt, S. B. (2020). Giving time: Examining sector differences in volunteering intensity. *Journal of Public Administration Research and Theory*, *30*(1), 22-40.

[Full Text](Holt2019JPART.pdf)