---
title: "Schools, Diversity, and PSM"
---

## When Knowing is Caring: Examining the Relationship Between Diversity Exposure and PSM.

### Abstract

While public service motivation (PSM) provides an important theory for understanding the motivations that underpin public sector worker behavior, theoretical connections to the institutional forces that produce and shape PSM remains underexamined. Given other-orientated motives that define part of PSM, exposure to peers from a variety of social backgrounds presents an input that may shape PSM earlier in life. Drawing on insights from intergroup contact theory, we use a nationally representative dataset of high school sophomores to examine the effect of school-level diversity along demographic and socioeconomic dimensions on students’ PSM-related values. Specifically, we use a fixed-effects approach to isolate the contribution of 10th grade exposure to students of a different race or socioeconomic background on 12th grade measures of PSM-related values. We find attending schools with a balanced mix of different-race students has a large and statistically significant impact on students’ PSM-related values by the end of secondary school.

#### Citation
Holt, S., & Choi, H. (2022). When Knowing is Caring: Examining the Relationship Between Diversity Exposure and PSM. *Review of Public Personnel Administration*, *42*(2), 226–257.

[Full Text](HoltChoi2020ROPPA.pdf)
