---
title: "Research"
---

My research to date can be found here and is organized by broad topic and (roughly) reverse chronological order. The links in the sidebar provide a page for each paper with an abstract and links to the full paper.

### Teachers, Schools, and Education

1.  **Holt, S. B.,** Vinopal, K., Choi, H., & Sorensen, L. C. (2022). [Strictly Speaking: Examining Teacher Use of Punishments and Student Outcomes.](referrals.qmd) *Working Paper*.

2.  Gershenson, S., **Holt, S. B.**, & Tyner, A. (2022). [Making the Grade: The Effect of Teacher Grading Standards on Student Outcomes.](grading.qmd) *Working Paper*.

3.  **Holt, S. B.** (2022). For the children? Teachers motivation and systems for recruitment, retention, and evaluation. In *Research Handbook on Motivation in Public Administration*. Edward Elgar Publishing.

4.  Sorensen, L. C., & **Holt, S. B.** (2021). [Sorting it out: The effects of charter expansion on teacher and student composition at traditional public schools.](charter.qmd) *Economics of Education Review*, *82*, 102095.

5.  **Holt, S. B.**, Wang, R., & Gershenson, S. (2020). [Stress Test: Examining the Evolution of Teachers' Mental Health Over Time.](mentalhealth.qmd) *Working Paper*.

6.  Gershenson, S., & **Holt, S. B.** (2015). [Gender gaps in high school students' homework time.](homework.qmd) *Educational Researcher*, *44*(8), 432-441.

### Demographic Representation

1.  Vinopal, K., & **Holt, S. B.** (2019). [Rookie mistakes: The interplay of teacher experience and racial representation.](rookie.qmd) *Educational Researcher*, *48*(7), 421-437.

2.  Johnston, J. M., & **Holt, S. B.** (2021). [Examining the influence of representative bureaucracy in public and private prisons.](prisons.qmd) *Policy Studies Journal*, *49*(2), 516-561.

3.  Amirkhanyan, A. A., **Holt, S. B.**, McCrea, A. M., & Meier, K. J. (2019). [Managing racial diversity: Matching internal strategies with environmental needs.](nursinghome.qmd) *Public Administration Review*, *79*(1), 69-81.

4.  **Holt, S. B.**, & Gershenson, S. (2019). [The impact of demographic representation on absences and suspensions.](absences.qmd) *Policy Studies Journal*, *47*(4), 1069-1099.

5.  Gershenson, S., **Holt, S. B.**, & Papageorge, N. W. (2016). [Who believes in me? The effect of student--teacher demographic match on teacher expectations.](expectations.qmd) *Economics of Education Review*, *52*, 209-224.

### Motivation

1. **Holt, S. B.,** & Choi, H. (2020). [When Knowing is Caring: Examining the Relationship Between Diversity Exposure and PSM.](knowyou.qmd) *Review of Public Personnel Administration*, *42*(2), 226-257.

1.  Piatak, J. S., & **Holt, S. B.** (2020). [Disentangling altruism and public service motivation: who exhibits organizational citizenship behaviour?.](ocb.qmd) *Public Management Review*, *22*(7), 949-973.

2.  Piatak, J. S., & **Holt, S. B.** (2020). [Prosocial behaviors: A matter of altruism or public service motivation?.](altruism.qmd) *Journal of Public Administration Research and Theory*, *30*(3), 504-518.

3.  Piatak, J. S., & **Holt, S. B.** (2021). *Public service motivation and public opinion: Examining antecedents and attitudes.* Cambridge University Press.

4.  **Holt, S. B.** (2020). [Giving time: Examining sector differences in volunteering intensity.](givetime.qmd) *Journal of Public Administration Research and Theory*, *30*(1), 22-40.

5.  AbouAssi, K., McGinnis Johnson, J., & **Holt, S. B.** (2021). [Job mobility among Millennials: Do they stay or do they go?.](millennials.qmd) *Review of Public Personnel Administration*, *41*(2), 219-249.

6.  **Holt, S. B.** (2018). [For those who care: The effect of public service motivation on sector selection.](sector.qmd) *Public Administration Review*, *78*(3), 457-471.

7.  **Holt, S. B.** (2019). [The influence of high schools on developing public service motivation.](civics.qmd) *International Public Management Journal*, *22*(1), 127-175.

### Burdens and Inequality

1.  **Holt, S. B.**, & Vinopal, K. (2021). [It's About Time: Examining Inequality in the Time Cost of Waiting.](waiting.qmd) *Working Paper*.
