<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.269">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Steve B. Holt - MPA Advising FAQ</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>


<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-sidebar docked nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Steve B. Holt</span>
    </a>
  </div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link active" href="./index.html" aria-current="page">
 <span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./research.html">
 <span class="menu-text">Research</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./teaching.html">
 <span class="menu-text">Teaching</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./cv.html">
 <span class="menu-text">Curriculum Vitae</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./resources.html">
 <span class="menu-text">Resources</span></a>
  </li>  
</ul>
              <div class="quarto-toggle-container">
                  <a href="" class="quarto-color-scheme-toggle nav-link" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
              </div>
              <div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
    <div class="container-fluid d-flex justify-content-between">
      <h1 class="quarto-secondary-nav-title">MPA Advising FAQ</h1>
      <button type="button" class="quarto-btn-toggle btn" aria-label="Show secondary navigation">
        <i class="bi bi-chevron-right"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header sidebar-header-stacked">
      <a href="./index.html" class="sidebar-logo-link">
      <img src="./profile.png" alt="" class="sidebar-logo py-0 d-lg-inline d-none">
      </a>
      </div>
      <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
      </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./resources.html" class="sidebar-item-text sidebar-link">Resources</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./mpa.html" class="sidebar-item-text sidebar-link active">MPA Advising FAQ</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./data.html" class="sidebar-item-text sidebar-link">Useful Data</a>
  </div>
</li>
    </ul>
    </div>
</nav>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#welcome-to-rockefeller-college" id="toc-welcome-to-rockefeller-college" class="nav-link active" data-scroll-target="#welcome-to-rockefeller-college">Welcome to Rockefeller College!</a></li>
  <li><a href="#overview-of-selecting-classes" id="toc-overview-of-selecting-classes" class="nav-link" data-scroll-target="#overview-of-selecting-classes">Overview of Selecting Classes</a>
  <ul class="collapse">
  <li><a href="#roles-and-functions" id="toc-roles-and-functions" class="nav-link" data-scroll-target="#roles-and-functions">Roles and Functions</a></li>
  <li><a href="#class-selection" id="toc-class-selection" class="nav-link" data-scroll-target="#class-selection">Class Selection</a></li>
  </ul></li>
  <li><a href="#common-paths" id="toc-common-paths" class="nav-link" data-scroll-target="#common-paths">Common Paths</a>
  <ul class="collapse">
  <li><a href="#first-and-second-semester" id="toc-first-and-second-semester" class="nav-link" data-scroll-target="#first-and-second-semester">First and Second Semester</a></li>
  <li><a href="#public-management" id="toc-public-management" class="nav-link" data-scroll-target="#public-management">Public Management</a></li>
  <li><a href="#public-policy" id="toc-public-policy" class="nav-link" data-scroll-target="#public-policy">Public Policy</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title d-none d-lg-block">MPA Advising FAQ</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<section id="welcome-to-rockefeller-college" class="level1">
<h1>Welcome to Rockefeller College!</h1>
<p>Hello and welcome to Rockefeller College. If you’re reading this, you probably were just admitted to the Rockefeller College Master’s of Public Administration Program, were assigned me as an advisor, and received a welcome email from me with a link to this post. (If you’re reading this because you were exploring my site and stumbled upon this post, go ahead and click away - this will be quite irrelevant to you.) Perhaps you’re wondering why I have directed you to a post on my professional website as an incoming advisee. Well, in my time at Rockefeller College, I’ve begun to realize that many students enter the program a little confused about navigating the bureaucracy of a university, a little confused about who to go to for what information, and anxious to get quick resolutions to these problems. I’ve also come to realize that I field many of the same questions repeatedly early on so I have found life might be a little easier for all involved if I simply created a central repository to house all of this information as a starting point for most common questions.</p>
<p>I will structure this post with a general overview of the process for selecting classes, a more detailed set of starting semester courses, and some thoughts on common paths among students typically assigned to me for advising.</p>
</section>
<section id="overview-of-selecting-classes" class="level1">
<h1>Overview of Selecting Classes</h1>
<section id="roles-and-functions" class="level2">
<h2 class="anchored" data-anchor-id="roles-and-functions">Roles and Functions</h2>
<p>So why would I start with class selection? Well, for starters, my primary role in your time at the university is to make sure you stay on track to fulfill your degree requirements and provide insight and advice from time-to-time on things that might shape your early career path. Of course, there might be a whole host of other issues that crop up in your time at Rockefeller, from financial aid to taking temporary leaves to career and job opportunities. I find many students enter the program a little confused on where to go for information on which things, so here’s an incomplete list of people and places to get important information.</p>
<ol type="1">
<li><p><a href="https://www.albany.edu/rockefeller/student-faculty-resources">Your MPA Program Handbook</a>. I know - this sounds a little trite. But the faculty and staff poured a lot of time and thought into the design and information in the MPA Program Manual and it will always be the best place to start a search for college policies, program requirements, and directory informaion.</p></li>
<li><p>The Director of Internships and Career Services. If you have any questions or concerns about internship requirements (or waivers!) or internship/job postings, the Director should be the first person you email. In fact, this person is so important for your success, I strongly recommend you set up a meeting with them during your first semester to cover career goals and interests and get an early understanding of career opportunities. You can email career services here for any career and internship needs: rockefeller.careers@albany.edu.</p></li>
<li><p>The MPA Director. Currently, the MPA Director is Dr.&nbsp;Ellen Rubin and for advanced programmatic issues - credit transfers, issues with a class, or other more technical issues with the program - she is the person you should reach out to first (erubin@albany.edu).</p></li>
<li><p>Rockefeller College Graduate Services. We have staff that handle a range of other issues, from problems with accessing various systems to answering questions unrelated to class-taking. Email rockgradservices@albany.edu and they will either handle the issue directly or loop in the appropriate staff person to do so.</p></li>
</ol>
<p>As you can see, there’s a lot of support for any issues that might come up. As your academic advisor, I play a very specific role in your time at the program and to save yourself time and headaches, I find that it’s good to know where to go for all the other things that might come up.</p>
</section>
<section id="class-selection" class="level2">
<h2 class="anchored" data-anchor-id="class-selection">Class Selection</h2>
<p>Selecting classes in Rockefeller is the primary time you will be consulting me. I will lay out some guidelines about classes to take later in another section, but here, it’s useful to have an overview of how you should approach registration. My role is to i) make sure you are fulfilling the program requirements in a timely manner and ii) provide advice on course selection when needed. Toward that end, here is how the class selection process should look in a typical situation:</p>
<ol type="1">
<li><p>Access the schedule of classes website through the Registrar’s Office on the University at Albany website. You can use this <a href="https://www.albany.edu/registrar/schedule-classes">link</a>. Start by selecting the upcoming semester in the dropdown, make sure you select Graduate Classes only, and for most instances you will also be filtering by “RPAD” in the <em>Course Subject</em> field. Use this to peruse the courses available that semester and create your schedule of classes that fits your course requirements and scheduling needs.</p></li>
<li><p>Send me an email with i) a list of the classes you’ve taken to date in the program (if any) and ii) your proposed schedule for the upcoming semester. <strong>If needed</strong> request a meeting to discuss any questions you might have about courses to take (often, this is productive if there are two electives you are considering and unsure which would be a better fit with your long-term goals)</p></li>
<li><p>After confirming that your proposed schedule leaves you on track, I will send you an AVN.</p></li>
<li><p>Use the AVN to register.</p></li>
</ol>
<div class="callout-tip callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p>Outside of the occassional circumstance regarding an elective choice, you generally do not need to meet with me unless you really find yourself lost and in need of clarification. Students often feel obligated to request meetings, which slows down your registration process given scheduling conflicts, so I note this simply to underscore that there is no obligation for you to meet with me in this scheduling process if <em>you</em> don’t really need it.</p>
</div>
</div>
</section>
</section>
<section id="common-paths" class="level1">
<h1>Common Paths</h1>
<p>In this section, I go over some common paths through the program for students interested in public management or public policy concentrations (the students I most frequently advise). We have recently overhauled the MPA curriculum in a way that intends for students to be able to take electives earlier in their time at Rockefeller without necessarily completing the core in a strictly linear fashion.</p>
<section id="first-and-second-semester" class="level2">
<h2 class="anchored" data-anchor-id="first-and-second-semester">First and Second Semester</h2>
<p>The general way to understand the MPA program is 8 core courses for generalized skills and knowledge and 4 more specialized electives. In your first two semesters, there are three possible approaches.</p>
<ul>
<li><p>Approach 1 - my recommended approach for most students who know their intended concentration on entry (except for Public Policy students) - provides a steady way to progress through the core while adding electives each semester to develop your more specialized concentration skills.</p></li>
<li><p>Approach 2 - what I recommend for students on the fence between the two concentrations I advise (management or policy) <strong>OR</strong> who know from the start that they will be in the public policy concentration. For students on the fence, this approach gives you an early taste of what both concentrations emphasize to inform your decision without “wasting” an elective.<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a> For Public Policy students, this approach covers the prerequisites for the two required electives that have prerequisites.</p></li>
<li><p>Approach 3 - which I only recommend in circumstances where a student is truly and completely undecided in their concentration intentions - gives you an upfront spread of more general classes to help you answer that question before taking electives.</p></li>
</ul>
<table class="table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Semester</th>
<th>Approach 1</th>
<th>Approach 2</th>
<th>Approach 3</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>First</td>
<td>RPAD 500, RPAD 504, Elective 1</td>
<td>RPAD 500, RPAD 503, RPAD 505</td>
<td>RPAD 500, RPAD 501, RPAD 504</td>
</tr>
<tr class="even">
<td>Second</td>
<td>RPAD 502, RPAD 505, Elective 2</td>
<td>(if Policy) RPAD 504, RPAD 522, RPAD 643; (if Management) RPAD 505, RPAD 610, Elective 2</td>
<td>RPAD 503, RPAD 505, Elective 1</td>
</tr>
<tr class="odd">
<td>Going Forward</td>
<td>2 cores, 1 elective per semester</td>
<td>2 cores, 1 elective per semester</td>
<td>2 electives, 1 core per semester</td>
</tr>
</tbody>
</table>
<div class="callout-important callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Important
</div>
</div>
<div class="callout-body-container callout-body">
<p>A subtlety many students might not pickup on is that core classes are, by necessity, offered on a guaranteed and frequent schedule, while electives have a less gauranteed schedule in their cycling and offerings. While many of the electives offered in Rockefeller are cycled annually, some are cycled biennially. The unpredictability of scheduling becomes even more severe when considering electives operated by another department. Exploit the timing and scheduling flexibility to take an elective you <strong>really</strong> want to take the semester it’s offered because you don’t know if/when it will be offered again!</p>
</div>
</div>
<p>For filling in the “Elective 2” placeholders and thinking about your courses after the first two semesters, see my description of each concentration below and the key classes to look out for on the schedule.</p>
</section>
<section id="public-management" class="level2">
<h2 class="anchored" data-anchor-id="public-management">Public Management</h2>
<p>The public management concentration focuses on key concepts and skills for managing public organizations - things like managing personnel, measuring the performance of both individuals and programs your organization operates, and thinking about contracts and grants (and the entities receiving them). The primary aim of taking this concentration is to learn how to manage the people and projects that make government run, regardless of what area of government you would like to be operating within. As you may have noticed, RPAD 610 is required for the concentration and I recommend taking it in your first semester if you are following approach 1 (i.e., you are coming in knowing you want to be in the public management concetration) or your second semester if you have decided to go the public management route after entering undecided.</p>
<p>From there, my general recommendation is you take the following classes <strong>as they are available in scheduling</strong> following the 1 elective per semester approach:</p>
<ul>
<li>RPAD 532 Performance Measurement and Contracting</li>
<li>RPAD 615 Strategic Planning and Management</li>
</ul>
<p>This leaves you with one elective to explore other topics or areas of interest to you. I suggest using it to take either RPAD 626 (Program Evaluation) as it provides a broadly applicable skillset <strong>or</strong> a policy topics class based on your area of content interest (e.g., health policy, environmental policy, education policy - see the policy concentration in the handbook/below). If you have a job in a particular agency in mind (e.g., New York State Education Department), using your elective on a content class in that department’s area can help signal your interest and knowledge on the front end and catch you up on the broader sets of issues and current debates for helping your work once you get started.</p>
<p>A good example plan:</p>
<table class="table">
<colgroup>
<col style="width: 52%">
<col style="width: 47%">
</colgroup>
<thead>
<tr class="header">
<th>Semester</th>
<th>Classes</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>First</td>
<td>RPAD 500, RPAD 504, RPAD 610</td>
</tr>
<tr class="even">
<td>Second</td>
<td>RPAD 502, RPAD 501, RPAD 532 OR RPAD 615 (pending availability)</td>
</tr>
<tr class="odd">
<td>Third</td>
<td>RPAD 506, RPAD 505, RPAD 532 OR RPAD 615 (whichever not taken)</td>
</tr>
<tr class="even">
<td>Fourth</td>
<td>RPAD 503, RPAD 507, RPAD 626 OR Policy Topic Elective</td>
</tr>
</tbody>
</table>
</section>
<section id="public-policy" class="level2">
<h2 class="anchored" data-anchor-id="public-policy">Public Policy</h2>
<p>The policy concentration has two “flavors” that can help you better understand it - an applied economics approach for assessing the potential (and observed!) impacts of government policies and programs and a political science approach that focuses on the policy process and the actors and institutions that shape government policy. However, unlike the public management concentration, the Public Policy concentration carries a little less flexibility in your coursework and sequencing. While generally we have moved away from specific pathing in our curriculum, the Policy concentration covers some more advanced technical material in its core - material that necessitates some prerequisite knowledge to get the most out of it. I think it’s generally a good idea to take RPAD 503 (a prerequisite for RPAD 643) and RPAD 505 (a prerequisite for RPAD 626) in your first semester if you know you are going to be a public policy concentration student. From there, you will take both RPAD 522 (Politics and Policy) and RPAD 643 (Economics of Public Policy) as they are available (every Spring semester). You will then take RPAD 626 in your second Fall semester. Finally, I recommend dedicating your last elective either to one of the content area policy classes (e.g., health, environmental, or education policy) that aligns with your interests or to an advanced econometrics class if possible (RPAD 517 or a more advanced class - talk to me if you are interested in taking this route).</p>
<p>For students interested in education, urban, health, or criminal justice policy who missed out on the RPAD elective when it was offered, I strongly recommend looking at Graduate Level classes in the School of Education, Public Health, Urban Planning, or Criminal Justice. Classes with policy in the name are often good crossover classes for our students, but that is the sort of thing to put in your email to me and that might warrant a meeting and conversation.</p>
<div class="callout-note callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>This is a suggested path to make things clear and ensure you cover your bases with classes offered on a regular and predictable schedule. However, if any of the three electives is just not your cup of tea, you can substitute it for an elective of your choice. You should enter as if you will take these three electives though so that you do not get hung up by pre-requisites.</p>
</div>
</div>
<p>A good example plan:</p>
<table class="table">
<thead>
<tr class="header">
<th>Semester</th>
<th>Classes</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>First</td>
<td>RPAD 500, RPAD 503, RPAD 505</td>
</tr>
<tr class="even">
<td>Second</td>
<td>RPAD 504, RPAD 643, RPAD 522</td>
</tr>
<tr class="odd">
<td>Third</td>
<td>RPAD 501, RPAD 502, RPAD 626</td>
</tr>
<tr class="even">
<td>Fourth</td>
<td>RPAD 506, RPAD 507, Policy Topic Elective OR RPAD 517</td>
</tr>
</tbody>
</table>


</section>
</section>


<div id="quarto-appendix" class="default"><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Footnotes</h2>

<ol>
<li id="fn1"><p>Of course, there is no such thing as a truly wasted class as all knowledge, growth, and experience has intrinsic value, particularly when creatively applied :).<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  let localAlternateSentinel = 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>